/// CalculationEngine.swift — MortgageCalculator
///
/// Čistý výpočetní engine bez závislosti na SwiftUI nebo Observation.
/// Všechny funkce jsou pure — stejné vstupy vždy produkují stejné výstupy.
/// Testovatelný nezávisle na UI.

import Foundation

enum CalculationEngine {

    // MARK: - Annuity

    /// Měsíční anuitní splátka: P × r × (1+r)^n / ((1+r)^n − 1)
    static func monthlyPayment(principal: CZK, annualRate: Percent, years: Years) -> CZK {
        let r = annualRate / 100 / 12
        let n = years * 12
        guard r > 0 else { return principal / n }
        return principal * r * pow(1 + r, n) / (pow(1 + r, n) - 1)
    }

    /// Měsíční splátka po refixaci — přepočtená ze zůstatku a zbývající doby.
    static func monthlyPaymentAfterRefix(_ inputs: MortgageInputs) -> CZK {
        guard inputs.useRefixation else { return 0 }
        let r = inputs.interestRate / 100 / 12
        let mp = monthlyPayment(principal: inputs.mortgageAmount,
                                annualRate: inputs.interestRate,
                                years: inputs.mortgageYears)
        var bal = inputs.mortgageAmount
        for _ in 1...(max(1, Int(inputs.refixYear)) * 12) {
            guard bal > 0 else { break }
            let interest = bal * r
            bal = max(0, bal - (mp - interest))
        }
        let remainingMonths = (inputs.mortgageYears - inputs.refixYear) * 12
        let r2 = inputs.refixRate / 100 / 12
        guard bal > 0, remainingMonths > 0 else { return 0 }
        guard r2 > 0 else { return bal / remainingMonths }
        return bal * r2 * pow(1 + r2, remainingMonths) / (pow(1 + r2, remainingMonths) - 1)
    }

    // MARK: - Tax

    /// Výpočet daně z nájmu dle zvoleného režimu (§ 9 ZDP).
    /// Skutečné náklady zahrnují úroky, opravy, správu, pojištění i SVJ.
    static func computeTax(
        rent: CZK, interest: CZK, repairs: CZK,
        management: CZK, insurance: CZK, svj: CZK,
        includeTax: Bool, taxMode: TaxMode, taxRate: Percent
    ) -> CZK {
        guard includeTax else { return 0 }
        let base: CZK
        switch taxMode {
        case .pausalni:
            base = rent * 0.70
        case .skutecne:
            base = max(0, rent - interest - repairs - management - insurance - svj)
        }
        return base * taxRate / 100
    }

    // MARK: - Auto Extra Payments

    /// Vypočítá automatické mimořádné splátky z nájmu.
    /// Simuluje splácení rok po roku, generuje splátky jen dokud dluh > 0.
    /// Pure funkce — vrací nový array, nemutuje žádný stav.
    static func autoExtraPayments(_ inputs: MortgageInputs) -> [ExtraPayment] {
        guard inputs.useRentAsExtraPayments else { return [] }

        let effectiveMonths = 12 - inputs.vacancyMonths
        let mp = monthlyPayment(principal: inputs.mortgageAmount,
                                annualRate: inputs.interestRate,
                                years: inputs.mortgageYears)
        var r = inputs.interestRate / 100 / 12
        var currentMp = mp
        let nYears = max(1, Int(inputs.mortgageYears))
        var balance = inputs.mortgageAmount
        var result: [ExtraPayment] = []

        for year in 1...nYears {
            guard balance > 0 else { break }

            let annualRent = inputs.monthlyRent * effectiveMonths
                * pow(1 + inputs.rentGrowthPct / 100, Double(year - 1))

            // Refixace
            if inputs.useRefixation && year == Int(inputs.refixYear) + 1 {
                let remaining = Double((nYears - Int(inputs.refixYear)) * 12)
                let r2 = inputs.refixRate / 100 / 12
                r = r2
                if r2 > 0, remaining > 0 {
                    currentMp = balance * r2 * pow(1+r2, remaining) / (pow(1+r2, remaining) - 1)
                } else if remaining > 0 {
                    currentMp = balance / remaining
                }
            }

            // 12 měsíčních splátek
            for _ in 1...12 {
                guard balance > 0 else { break }
                let interest = balance * r
                let principal = min(currentMp - interest, balance)
                balance = max(0, balance - principal)
            }

            // Manuální mimořádné splátky
            let manualExtra = inputs.extraPayments
                .filter { $0.year == year && $0.isEnabled }
                .reduce(0) { $0 + $1.amount }
            balance = max(0, balance - min(manualExtra, balance))

            guard balance > 0 else { break }
            balance = max(0, balance - min(annualRent, balance))
            result.append(ExtraPayment(year: year, amount: annualRent, autoGenerated: true))
        }

        return result
    }

    // MARK: - Amortization Schedule

    /// Vypočítá kompletní amortizační harmonogram rok po roku.
    /// Pure funkce — přijímá vstupy, vrací [YearData].
    static func computeSchedule(_ inputs: MortgageInputs,
                                allExtraPayments: [ExtraPayment]) -> [YearData] {
        let mp = monthlyPayment(principal: inputs.mortgageAmount,
                                annualRate: inputs.interestRate,
                                years: inputs.mortgageYears)
        var r = inputs.interestRate / 100 / 12
        var currentMp = mp
        let nYears = max(1, Int(inputs.mortgageYears))
        let repairCycle = max(1, Int(inputs.largeRepairEveryNYears))

        var balance = inputs.mortgageAmount
        var cum = -inputs.downPayment
        var cumInterest: CZK = 0
        var result: [YearData] = []

        for year in 1...nYears {
            let isRefixYear = inputs.useRefixation && year == Int(inputs.refixYear) + 1 && balance > 0
            if isRefixYear {
                let remainingMonths = Double((nYears - Int(inputs.refixYear)) * 12)
                let r2 = inputs.refixRate / 100 / 12
                r = r2
                if r2 > 0, remainingMonths > 0 {
                    currentMp = balance * r2 * pow(1+r2, remainingMonths) / (pow(1+r2, remainingMonths) - 1)
                } else if remainingMonths > 0 {
                    currentMp = balance / remainingMonths
                }
            }

            let effectiveMonths = 12 - inputs.vacancyMonths
            let actualRent = inputs.monthlyRent * effectiveMonths
                * pow(1 + inputs.rentGrowthPct / 100, Double(year - 1))

            let large = (year % repairCycle == 0) ? inputs.largeRepairAmount : 0.0
            let totalRepair = inputs.annualRepairs + large

            let mgmtFee = inputs.includeManagement ? actualRent * inputs.managementFeePct / 100 : 0
            let insurance = inputs.annualInsurance
            let svj = inputs.monthlySVJ * 12

            let extra = allExtraPayments.filter { $0.year == year && $0.isEnabled }
                                        .reduce(0.0) { $0 + $1.amount }

            let propValue = inputs.includeAppreciation
                ? inputs.propertyPrice * pow(1 + inputs.propertyAppreciationPct / 100, Double(year))
                : inputs.propertyPrice

            var yi: CZK = 0, yp: CZK = 0
            var usedPayment = currentMp * 12

            if balance <= 0 {
                let tax = computeTax(rent: actualRent, interest: 0, repairs: totalRepair,
                                     management: mgmtFee, insurance: insurance, svj: svj,
                                     includeTax: inputs.includeTax, taxMode: inputs.taxMode,
                                     taxRate: inputs.taxRate)
                cum += actualRent - totalRepair - tax - mgmtFee - insurance - svj
                result.append(YearData(
                    year: year, annualPayment: 0, interestPaid: 0, principalPaid: 0,
                    extraPayment: 0, remainingBalance: 0, cumulativeInterest: cumInterest,
                    rentalIncome: actualRent, regularRepair: inputs.annualRepairs, largeRepair: large,
                    taxAmount: tax, isRefixYear: false,
                    managementFee: mgmtFee, insuranceCost: insurance, svjCost: svj,
                    propertyValue: propValue, cumulativeNet: cum
                ))
                continue
            }

            for _ in 1...12 {
                guard balance > 0 else { usedPayment -= currentMp; break }
                let interest = balance * r
                let principal = min(currentMp - interest, balance)
                yi += interest
                yp += principal
                balance = max(0, balance - principal)
            }

            let actualExtra = min(extra, balance)
            balance = max(0, balance - actualExtra)

            cumInterest += yi
            let tax = computeTax(rent: actualRent, interest: yi, repairs: totalRepair,
                                 management: mgmtFee, insurance: insurance, svj: svj,
                                 includeTax: inputs.includeTax, taxMode: inputs.taxMode,
                                 taxRate: inputs.taxRate)
            cum += actualRent - yi - totalRepair - tax - actualExtra - mgmtFee - insurance - svj

            result.append(YearData(
                year: year, annualPayment: usedPayment, interestPaid: yi,
                principalPaid: yp, extraPayment: actualExtra, remainingBalance: balance,
                cumulativeInterest: cumInterest, rentalIncome: actualRent,
                regularRepair: inputs.annualRepairs, largeRepair: large,
                taxAmount: tax, isRefixYear: isRefixYear,
                managementFee: mgmtFee, insuranceCost: insurance, svjCost: svj,
                propertyValue: propValue, cumulativeNet: cum
            ))
        }
        return result
    }
}
