/// Models.swift — MortgageCalculator
///
/// Domain modely: datové struktury bez závislosti na SwiftUI.
/// Použité v CalculationEngine i ve ViewModelu.

import Foundation

// MARK: - Tax Mode

/// Způsob výpočtu základu daně z příjmu z nájmu.
enum TaxMode: String, CaseIterable, Identifiable, Codable {
    /// Základ daně = 70 % příjmu (30 % paušální výdaj dle § 9 ZDP).
    case pausalni = "Paušální výdaj 30 %"
    /// Základ daně = příjem − úroky − opravy (skutečné výdaje, min. 0).
    case skutecne  = "Skutečné náklady"
    var id: String { rawValue }
}

// MARK: - Extra Payment

/// Jednorázová mimořádná splátka jistiny v konkrétním roce.
/// Lze ji dočasně vypnout togglem (isEnabled = false) bez smazání.
struct ExtraPayment: Identifiable {
    let id = UUID()
    var year: Int
    var amount: CZK
    var isEnabled: Bool = true
    var autoGenerated: Bool = false
}

// MARK: - Year Data

/// Vypočtená data pro jeden rok splácení hypotéky.
/// Immutable struct — všechny hodnoty jsou nastaveny při inicializaci.
struct YearData: Identifiable {
    let id = UUID()
    let year: Int

    /// Součet pravidelných měsíčních splátek za rok. Po splacení je 0.
    let annualPayment: CZK

    /// Část pravidelných splátek, která šla na úroky (náklad).
    let interestPaid: CZK

    /// Část pravidelných splátek, která šla na jistinu (snižuje dluh).
    let principalPaid: CZK

    /// Mimořádná splátka jistiny zaplacená nad rámec pravidelné splátky.
    let extraPayment: CZK

    /// Zbývající nesplacená jistina na konci roku.
    let remainingBalance: CZK

    /// Kumulativní součet úroků od roku 1 do tohoto roku (pro graf).
    let cumulativeInterest: CZK

    /// Skutečný roční příjem z nájmu (roste každý rok o rentGrowthPct).
    let rentalIncome: CZK

    /// Roční náklady na pravidelnou drobnou údržbu.
    let regularRepair: CZK

    /// Náklady na velkou údržbu (nenulové jen v roce N, 2N, 3N, …).
    let largeRepair: CZK

    /// Daň z příjmu z nájmu (0 pokud je includeTax = false).
    let taxAmount: CZK

    /// True pokud v tomto roce nastala refixace sazby.
    let isRefixYear: Bool

    /// Poplatek za správu nemovitosti (% z nájmu).
    let managementFee: CZK
    /// Roční pojištění nemovitosti.
    let insuranceCost: CZK
    /// Roční příspěvek SVJ / fond oprav.
    let svjCost: CZK
    /// Hodnota nemovitosti na konci roku (se zhodnocením).
    let propertyValue: CZK

    var repairCost: CZK        { regularRepair + largeRepair }
    var isLargeRepairYear: Bool { largeRepair > 0 }
    var totalPaidOut: CZK      { annualPayment + extraPayment }
    var operatingCosts: CZK    { managementFee + insuranceCost + svjCost }

    /// Čistý roční výsledek: nájem − úroky − opravy − provoz − daň.
    var netYear: CZK { rentalIncome - interestPaid - repairCost - taxAmount - operatingCosts }

    var cumulativeNet: CZK
}

// MARK: - Mortgage Inputs

/// Snapshot všech vstupních parametrů — předávaný do CalculationEngine.
/// Odděluje UI stav od čistého výpočtu.
struct MortgageInputs {
    // Nemovitost
    var propertyPrice: CZK = 9_900_000
    var ownCapitalPct: Percent = 10
    var includeReconstruction: Bool = false
    var reconstructionAmount: CZK = 1_000_000
    var includeAppreciation: Bool = false
    var propertyAppreciationPct: Percent = 3.0

    // Hypotéka
    var mortgageYears: Years = 30
    var interestRate: Percent = 4.79

    // Refixace
    var useRefixation: Bool = false
    var refixYear: Years = 5
    var refixRate: Percent = 5.0

    // Příjmy z nájmu
    var monthlyRent: CZK = 25_000
    var rentGrowthPct: Percent = 2.0
    var vacancyMonths: Months = 1

    // Provozní náklady
    var includeManagement: Bool = false
    var managementFeePct: Percent = 10
    var annualInsurance: CZK = 8_000
    var monthlySVJ: CZK = 3_000

    // Opravy
    var annualRepairs: CZK = 130_000
    var largeRepairAmount: CZK = 300_000
    var largeRepairEveryNYears: Years = 10

    // Daň
    var includeTax: Bool = true
    var taxMode: TaxMode = .pausalni
    var taxRate: Percent = 15

    // Mimořádné splátky
    var extraPayments: [ExtraPayment] = []
    var useRentAsExtraPayments: Bool = false

    // Zhodnocení & srovnání
    var includeOpportunityCost: Bool = false
    var alternativeReturnPct: Percent = 7.0
    var includeInflation: Bool = false
    var inflationRate: Percent = 2.5

    // Odvozené
    var totalPropertyCost: CZK {
        includeReconstruction ? propertyPrice + reconstructionAmount : propertyPrice
    }
    var mortgageAmount: CZK { totalPropertyCost * (1 - ownCapitalPct / 100) }
    var downPayment: CZK    { totalPropertyCost * ownCapitalPct / 100 }
}
